export const routes = {
  home: '/',
  register: '/register',
  about: '/about',
  contact: '/contact',
  catalog: '/catalog',
  cart: '/cart',
  favorites: '/favorites',
  terms_and_conditions: '/terms-and-conditions',
  cookies_policy: '/cookies-policy',
  privacy_policy: '/privacy-policy',
  profile: '/profile',
  profile_edit: '/profile/edit',
  profile_orders: '/profile/orders',
  profile_auth: '/profile/auth',
  profile_organization: '/profile/organization',
  profile_offer: '/profile/offer',
  profile_offer_create: '/profile/offer/create',
}